### ISSUE TITLE
Nack and requeue: false?

### ISSUE THREAD

**Issue by damien-roche** [conduitframework/conduit_amqp#11]
I currently have a `nack` in my subscriber `process` function, and it appears the message is requeued.

I cannot find any documentation about how to set requeue to false. I did find this:

https://github.com/conduitframework/conduit_amqp/blob/45dbbf04c644f0d5a88b1941b138a5b5125959de/lib/conduit_amqp/task.ex#L21

```
    case broker.receives(name, message) do
      %Message{status: :ack} ->
        Basic.ack(chan, props.delivery_tag)

      %Message{status: :nack} ->
        Basic.reject(chan, props.delivery_tag)
    end
```

And found an example of a `Basic.reject` here in `amqp` package:

`:ok = Basic.reject channel, tag, requeue: false`

I'm wondering if this is possible with conduit without forking/patching?

**Comment by blatyo** [comment]
I typically ack messages I don't want to requeue. I'm not aware of any benefit to nacking messages that you don't want requeued.

These two plugs can help with that:
* https://hexdocs.pm/conduit/Conduit.Plug.MessageActions.html#ack/3
* https://hexdocs.pm/conduit/Conduit.Plug.AckException.html#content

Also, if you're interested in doing something with the failed messages, you can use the DeadLetter plug to send them to another queue and process them more generously there.

https://hexdocs.pm/conduit/Conduit.Plug.DeadLetter.html#content

**Comment by damien-roche** [comment]
Thanks. The reason for nacking/rejecting without requeue was indeed to get them into a dead letter exchange. However, I've opted for using policies as this allows me to configure the dead letter routing across a pattern of exchanges/queues without [re-]declaring them.

I'll have a look into the plugs to see if they'll help.
