### ISSUE TITLE
Request for guidance: direct-reply-to/RPC-style message flows

### ISSUE THREAD

**Issue by shanesveller** [conduitframework/conduit_amqp#12]
This library seems incredible after spending an hour or two with it last week! 🎉 🎊 

My employer, @citybaseinc, is considering adopting this project as part of our event-bus architecture, but in its current iteration, we are currently taking advantage of the request-response message flow that is [possible in NATS](https://nats.io/documentation/writing_applications/publishing/#request-reply). (This is not required reading for the purposes of this discussion.) We're using this model for RPC purposes, and RabbitMQ has [similarly capable features](https://www.rabbitmq.com/direct-reply-to.html) that we'd like to enable in our chosen client library in order to perform a more complete comparison between NATS and RabbitMQ.

Can you please mull this over and suggest likely areas of the codebase or API contract that aren't currently compatible if this message flow was to be fully supported at the same high quality of the existing feature set? We'd be willing to (at very least) spike on an implementation after some pointers, if that kind of contribution would be welcome. I hope not to maintain a private fork or dip down into the underlying `amqp` library with any regularity, but I also realize this is not a universal use-case.

The immediate concern I have myself is what existing or new component might handle and store what amounts to a transient "mailbox switchboard". This would provide the final leg of an incoming reply's journey, from the supervised Conduit subscriber to a sibling Elixir process that is currently awaiting a reply message from an earlier publish. I'm not sure if that can or should live in the local subscriber module. I'm also not even sure how I would start to implement that without digging deep into the guts of `conduit_amqp`. I was able to make this work at least partially successfully with the underlying `amqp` library, so that's encouraging.

We also need to be able to subscribe to the "magic" queue name mentioned in the linked document above. This requires us to pass `no_ack: true` to `AMQP.Basic.consume`. I _think_ I had that working with a `conduit_amqp` diff similar to the following:

```diff
diff --git a/lib/conduit_amqp/sub.ex b/lib/conduit_amqp/sub.ex
index 7bf4216..1a14c82 100644
--- a/lib/conduit_amqp/sub.ex
+++ b/lib/conduit_amqp/sub.ex
@@ -60,9 +60,10 @@ defmodule ConduitAMQP.Sub do
   def handle_info(:connect, %{status: :disconnected, broker: broker, name: name, opts: opts} = state) do
     case ConduitAMQP.with_conn(broker, &Channel.open/1) do
       {:ok, chan} ->
+        consume_opts = Keyword.get(opts, :consume_opts, [])
         Process.monitor(chan.pid)
         Basic.qos(chan, opts)
-        Basic.consume(chan, opts[:from] || Atom.to_string(name))
+        Basic.consume(chan, opts[:from] || Atom.to_string(name), nil, consume_opts)
         Logger.info("#{inspect(self())} Channel opened for subscription #{inspect(name)}")
 
         {:noreply, %{state | chan: chan, status: :connected}}
```

I wasn't immediately successful in declaring a subscriber for the `amq.rabbitmq.reply-to` pseudo-queue mentioned in the linked RabbitMQ documentation. I'm not able to recall what specific error I ran into, and I unfortunately didn't commit the code that generated it, but I also had trouble publishing a `Message` with the `reply-to` header included. Odds are pretty good that it may have stemmed from the prior issue.

Thanks for any information or clarity you can provide!

**Comment by blatyo** [comment]
> This library seems incredible after spending an hour or two with it last week! 🎉 🎊

Glad you're enjoying it

> We also need to be able to subscribe to the "magic" queue name mentioned in the linked document above. This requires us to pass `no_ack: true` to `AMQP.Basic.consume`. I _think_ I had that working with a `conduit_amqp` diff similar to the following:

Please submit a PR for that. We can work through this in small increments. This library ideally shouldn't do anything to prevent you from using a feature of RabbitMQ. So, this is a clear win.

> My employer, @CityBaseInc, is considering adopting this project as part of our event-bus architecture, but in its current iteration, we are currently taking advantage of the request-response message flow that is [possible in NATS](https://nats.io/documentation/writing_applications/publishing/#request-reply). (This is not required reading for the purposes of this discussion.) We're using this model for RPC purposes, and RabbitMQ has [similarly capable features](https://www.rabbitmq.com/direct-reply-to.html) that we'd like to enable in our chosen client library in order to perform a more complete comparison between NATS and RabbitMQ.

> Can you please mull this over and suggest likely areas of the codebase or API contract that aren't currently compatible if this message flow was to be fully supported at the same high quality of the existing feature set? We'd be willing to (at very least) spike on an implementation after some pointers, if that kind of contribution would be welcome. I hope not to maintain a private fork or dip down into the underlying `amqp` library with any regularity, but I also realize this is not a universal use-case.

> The immediate concern I have myself is what existing or new component might handle and store what amounts to a transient "mailbox switchboard". This would provide the final leg of an incoming reply's journey, from the supervised Conduit subscriber to a sibling Elixir process that is currently awaiting a reply message from an earlier publish. I'm not sure if that can or should live in the local subscriber module. I'm also not even sure how I would start to implement that without digging deep into the guts of `conduit_amqp`. I was able to make this work at least partially successfully with the underlying `amqp` library, so that's encouraging.

I'd like to see something like this built outside the library first and then consider how it could be brought in. Perhaps it could start as a branch in this repo https://github.com/conduitframework/conduit_amqp_example, so we can discuss.

My initial thinking is that you could start a "reply-to" Registry process. Then define a function, something like (completely untested): 

``` elixir
defmodule ConduitAMQP.RPC do
  def request(message, route, opts) do
    registry = Keyword.get(opts, :registry)
    broker = Keyword.get(opts, :broker)
    timeout = Keyword.get(opts, :timeout)
    reply_to = UUID.uuid4()

    Registry.register(registry, reply_to, self())
    broker.publish(message, route, opts)

    receive do
      {:conduit_amqp_rpc_reply, ^reply_to, message} ->
         {:ok, message}
    after
      ^timeout -> {:error, :timeout}
    end
  end
end
``` 

Then, you'd define a subscriber to receive replies (also untested):

``` elixir
defmodule ConduitAMQP.RPC.Subscriber do
  use Conduit.Subscriber

  def process(message, opts) do
    registry = Keyword.get(opts, :registry)
    reply_to = get_header(message, "reply_to")

    with [{_, waiting_process}] <- Registry.lookup(registry, reply_to) do
      Process.send(waiting_process, {:conduit_amqp_rpc_reply, ^reply_to, message})
    end

    message
  end
end
```

You'd also need another subscriber for the server side of RPC, but I'm not sure if that'd be generic. Perhaps it would be if it did some routing. Mind trying that out?

Also, thanks for the well written issue!

**Comment by shanesveller** [comment]
Hello again - my employer has opted to discontinue any further research into AMQP for unrelated reasons, so I don't expect to be given time at work to attempt to hack on this further, and I don't currently use message queues in any side projects. Sorry! I feel especially guilty given the high quality, informative reply I received. 😞 

I'll leave it up to @blatyo for how he wants to address this GitHub issue, but I'm fine with closing it if that seems the most appropriate course.

**Comment by blatyo** [comment]
NBD, good luck!

**Comment by blatyo** [comment]
What are you using instead?

**Comment by shanesveller** [comment]
For now, we're going to re-invest in our existing approach using NATS that I mentioned in the original post. Both the server technology itself and the client we're building around the open-source `gnat` Hex package will need some very substantial investment to reach any meaningful parity with either AMQP or this library, but maybe one day we'll be able to contribute a Conduit (or Broadway!) driver for it. 🤞
