### ISSUE TITLE
Is it possible to pass in "arguments" for exchanges?

### ISSUE THREAD

**Issue by damien-roche** [conduitframework/conduit_amqp#9]
I'm using a dedupe plugin for RMQ and am struggling to pass in some required arguments when declaring an exchange. Any suggestions?

```
    exchange "my_exchange",
      type: :"x-message-deduplication",
      arguments: [{"x-cache-size", :short, 100}],
      durable: true
```

The dedupe plugin requires an argument to be present for `x-cache-size`, but cannot figure out even if `conduit_amqp` passes arguments? The documentation around exchange declare links to https://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.declare instead of documentation for conduit implementation.

From my understanding, conduit is using amqp under the hood? 

https://github.com/conduitframework/amqp#types-of-arguments-and-headers

There are examples of using arguments. However, no custom arguments are allowed (exchange declare only allows `alternate-exchange`).

I just wanted to confirm if that's the issue I'm running into and what would be the best way to modify this to my tastes. Are you passing arguments through to `amqp` and so I simply need to fork/modify that?

Thanks.

**Comment by blatyo** [comment]
Can you post the versions of your dependencies? `mix hex.outdated --all`

The options specified on the exchange are passed to amqp:
https://github.com/conduitframework/conduit_amqp/blob/master/lib/conduit_amqp/topology.ex#L33

The amqp you linked to was a fork, which is superseded by the official amqp package. If you look here, it passes the arguments along: 
https://github.com/pma/amqp/blob/master/lib/amqp/exchange.ex#L40

That means, if it's not getting passed along, it's likely an issue with `rabbit_common`, `amqp_client`, or one of their dependencies. Those are maintained by the creators of RabbitMQ.

You can do a really simple sanity check that it's not conduits fault, be adding an `IO.inspect(options)` inside this function in your deps folder:
https://github.com/pma/amqp/blob/master/lib/amqp/exchange.ex#L31

Then, just delete your `_build` folder and it should recompile with that change there, so you can see what options are getting passed down.

**Comment by damien-roche** [comment]
This is the error I receive when I attempt to declare the exchange as described above:

> [error] Channel closed, because {:shutdown, {:server_initiated_close, 406, "PRECONDITION_FAILED - Missing or invalid argument,           'x-cache-size' must be an integer greater than 0"}}

> [error] GenServer Brokers.MyBroker.Adapter.Setup terminating

> ** (stop) exited in: :gen_server.call(#PID<0.2834.0>, {:call, {:"exchange.declare", 0, "bulk_uptime_checks_exchangetest", "x-message-deduplication", false, true, false, false, false, [{"x-cache-size", :short, 100}]}, :none, #PID<0.2831.0>}, 60000)

It is being passed into a gen_server.call, but am wondering where that is?

I've outputted the options in that function and the custom arguments are indeed present. I'll dig more into `rabbit_common` and `amqp_client` tomorrow. Thanks.

**Comment by blatyo** [comment]
Don't know if this'll make a difference, but I notice the error says `'x-cache-size'` rather than `"x-cache-size"`. Perhaps try passing `'x-cache-size'` instead?

**Comment by damien-roche** [comment]
No go :/ That appears to be the response received from the RMQ server when attempting to declare the exchange.

But I may have isolated the problem. If I declare a direct exchange with `x-cache-size` in the arguments it works.. and the arguments show up in RMQ management. Turns out it might actually be something to do with my RMQ instance and the dedupe plugin I have installed. Either way, I doubt it is related to conduit.

Thanks for the response(s).

Btw.. I'd be interested to know if, in your experience of building the adapters, you'd advise switching out RMQ for something such as NSQ?

**Comment by blatyo** [comment]
I probably wouldn't pick NSQ (adapter not done yet) personally. It depends on what you're using the queue for. I think RMQ is the best I've seen for application to application communication. It supports a lot of patterns that you then don't have to build into your application. If you're building a data pipeline, I'd probably recommend Kafka (adapter forthcoming). If you're insistent on using a hosted service, I'd probably recommend AWS Kineses (also forthcoming), which is sort of like Kafka (though, I typically try to avoid things I can't run locally). If you're doing IOT, I'd probably recommend MQTT (soon to be released) and VerneMQ. If you wanted to do hosted for IOT, then AWS Kineses would probably be the choice again.
